In [2]:
import numpy as np
a=np.array([1,2,3])
a


array([1, 2, 3])

In [3]:
np.zeros(2)


array([0., 0.])

In [4]:
np.ones(2)

array([1., 1.])

In [6]:
np.ones(2,dtype=int)



array([1, 1])

In [8]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [9]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
arr=np.array([2,4,3,1,0,9])
np.sort(arr)

array([0, 1, 2, 3, 4, 9])

In [3]:
import numpy as np
a=np.array([[[0,1,2,3],[4,5,6,7]]])
a.ndim


3

In [5]:
a.size

8

In [6]:
a.shape

(1, 2, 4)

In [7]:
a=np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [12]:
b=a.reshape(4,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [14]:
a=np.arange(8)
a[2:7]

array([2, 3, 4, 5, 6])

In [15]:
a[1:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
a[:-1]

array([0, 1, 2, 3, 4, 5, 6])

In [17]:
import numpy as np

In [18]:
d=np.array([1,2])
ones=np.ones(2,dtype=int)
d+ones

array([2, 3])

In [19]:
d*ones

array([1, 2])

In [20]:
d-ones

array([0, 1])

In [21]:
d/ones

array([1., 2.])

In [23]:
rand=np.random.rand(4,2)
rand

array([[0.11601071, 0.69467762],
       [0.82696811, 0.90768493],
       [0.33467502, 0.13415503],
       [0.76107429, 0.79836289]])

In [25]:
np.random.randint(3)#random

1

In [31]:
l=np.linspace(5,2)#linspace
l

array([5.        , 4.93877551, 4.87755102, 4.81632653, 4.75510204,
       4.69387755, 4.63265306, 4.57142857, 4.51020408, 4.44897959,
       4.3877551 , 4.32653061, 4.26530612, 4.20408163, 4.14285714,
       4.08163265, 4.02040816, 3.95918367, 3.89795918, 3.83673469,
       3.7755102 , 3.71428571, 3.65306122, 3.59183673, 3.53061224,
       3.46938776, 3.40816327, 3.34693878, 3.28571429, 3.2244898 ,
       3.16326531, 3.10204082, 3.04081633, 2.97959184, 2.91836735,
       2.85714286, 2.79591837, 2.73469388, 2.67346939, 2.6122449 ,
       2.55102041, 2.48979592, 2.42857143, 2.36734694, 2.30612245,
       2.24489796, 2.18367347, 2.12244898, 2.06122449, 2.        ])

In [36]:
a=np.array([[1,2],[3,4]])# reshape and flatteem
a.reshape((1,4))
a.flatten()

array([1, 2, 3, 4])

In [40]:
a=np.array([1,2,3])#math operations 
b=np.array([4,5,6])
add=a+b
mul=a*b
sub=a-b
exp=np.exp(a)
print(add)
print(mul)
print(exp)
print(sub)

[5 7 9]
[ 4 10 18]
[ 2.71828183  7.3890561  20.08553692]
[-3 -3 -3]


In [41]:
d=np.array([[1,2,3],[4,5,6]])#stats operation
mean=np.mean(d)
median=np.median(d)
std=np.std(d)
print(mean)
print(median)
print(std)

3.5
3.5
1.707825127659933


In [43]:
d=np.array([1,2,3,4,5,6])
mask=d>3
mask

array([False, False, False,  True,  True,  True])

In [45]:
filtered=d[mask]
filtered

array([4, 5, 6])

In [48]:
a=np.arange(6790)
a

array([   0,    1,    2, ..., 6787, 6788, 6789])